### ISSUE TITLE
not working on 1.10

### ISSUE THREAD

**Issue by isamercan** [shtalinberg/django-amp-tools#2]
hey man, thanks for adding tool. im trying to add this app but not working on 1.10 . i think its about middleware issue but cant fix it.

MIDDLEWARE_CLASSES changed as MIDDLEWARE so how can we fix it?

**Comment by shtalinberg** [comment]
It's my config for 1.10.x
```
MIDDLEWARE_CLASSES = (
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware'
    'django.middleware.locale.LocaleMiddleware', 
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'amp_tools.middleware.AMPDetectionMiddleware',
)
```

**Comment by isamercan** [comment]
ok ic. i tried like that on my project and it works too. but as u can see MIDDLEWARE_CLASSES is no longer avaliable. so what should we do ?

**Comment by shtalinberg** [comment]
Yes, need adapt old, custom middleware for using the new setting MIDDLEWARE
but now worked in 1.10 with MIDDLEWARE_CLASSES.

**Comment by isamercan** [comment]
so can u guide me how can i ?

**Comment by shtalinberg** [comment]
0.2.0    - tested with  Django 1.11
