### ISSUE TITLE
not working on 1.11

### ISSUE THREAD

**Issue by mertcangokgoz** [shtalinberg/django-amp-tools#4]
````
    mw_instance = middleware(handler)
TypeError: object() takes no parameters

````

**Comment by CARocha** [comment]
but i am using 1.10.2 and not working why?

Django version 1.10.2, using settings 'website.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.

File "/home/user/project/django/virtuales/website/lib/python2.7/site-packages/django/core/handlers/base.py", line 82, in load_middleware
    mw_instance = middleware(handler)
TypeError: object() takes no parameters



this is my config
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.contrib.flatpages.middleware.FlatpageFallbackMiddleware',
    'django.middleware.gzip.GZipMiddleware',
    'amp_tools.middleware.AMPDetectionMiddleware',
]

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
    
        'OPTIONS': {
            'loaders': [
               'amp_tools.loader.Loader',
            ],
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

any tips helps??

**Comment by luizrrodrigues** [comment]
Same problem. Django 1.11
```
mw_instance = middleware(handler)
TypeError: object() takes no parameters
```

**Comment by bitcoinment** [comment]
Same problem

**Comment by shtalinberg** [comment]
0.2.0    - tested with  Django 1.11
